version: "3.8"

services:
  server:
    image: ndrek/fearlessdraft-server:${IMAGE_TAG}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      restart_policy:
        condition: any
    ports:
      - "8080:8080"